version: '3.8'

services:
  app:
    build: .
    container_name: storage-app
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - STORAGE_BASE_PATH=/var/storage
      - APP_BASE_URL=${APP_BASE_URL:-http://localhost:8080}
      - APP_CORS_ALLOWED_ORIGINS=${CORS_ORIGINS:-*}
    volumes:
      - storage-data:/var/storage
    networks:
      - coolify
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.storage-app.rule=Host(`storage.devyoussef.com`)"
      - "traefik.http.services.storage-app.loadbalancer.server.port=8080"
      - "traefik.http.routers.storage-app.tls=true"
      - "traefik.http.routers.storage-app.tls.certresolver=letsencrypt"

networks:
  coolify:
    external: true


volumes:
  storage-data:
